
#General settings
[general]
	#Adjust the color of the bubbles outline | args = r,g,b,a
	outlineColor = [35, 35, 35, 220]
	#Adjust the color of the bubbles inside | args = r,g,b,a
	insideColor = [236, 244, 255, 220]
	#Adjust the color of the bubbles text | args = r,g,b,a
	textColor = [35, 35, 35, 230]
	#Adjust duration time of bubbles
	#Range: 0 ~ 60
	durationBubbles = 6
	#Max Bubbles Stackable on a player's head
	#Range: > 0
	maxBubblesStack = 0
	#Max line width
	#Range: > 50
	lineWidth = 50
	#Size of bubble
	#Range: 0 ~ 20
	sizeBubble = 1
	#Enable Bubbles Listener
	bubblesListener = true
	#See the bubbles through blocks or not ( like name )
	throughBlock = true
	#Force Format chat is bubbles don't appear
	forceFormatChat = false

